name: Deploy Cloud Cost Guard
on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      - run: sam build --use-container
      - run: sam deploy --stack-name cloud-cost-guard --resolve-s3 --capabilities CAPABILITY_IAM \
             --parameter-overrides ReportsBucketName=${{ secrets.AWS_ACCOUNT_ID }}-ccg-reports
